---
all:
  children:
    bootstrap:
      hosts:
        # 192.168.0.177:
        rock-pi-4b:
    cluster:
      hosts:
        nodeprod01:
        nodeprod02:
        nodeprod03:
        nodeprod04:
        nodeprod05:
        nodeprod06:
    control_plane:
      hosts:
        nodecp01:
        nodecp02:
        nodecp03:
    workers:
      hosts:
        nodewk04:
        nodewk05:
        nodewk06:
