---
all:
  children:
    bootstrap:
      hosts:
        rock-pi-4b:
    cluster:
      hosts:
        nodetest01:
          ansible_host: 192.168.0.177
        # nodeprod01:
        #   ansible_host: 192.168.1.1
        # nodeprod02:
        #   ansible_host: 192.168.1.2
        # nodeprod03:
        #   ansible_host: 192.168.1.3
        # nodeprod04:
        #   ansible_host: 192.168.1.4
        # nodeprod05:
        #   ansible_host: 192.168.1.5
        # nodeprod06:
        #   ansible_host: 192.168.1.6
    control_plane:
      hosts:
        nodecp01:
        nodecp02:
        nodecp03:
    workers:
      hosts:
        nodewk04:
        nodewk05:
        nodewk06:
