---
# ansible-galaxy collection install -r requirements.yml
collections:
  - name: git+https://github.com/enricocirignaco/ansible.git#/ansible_collections/enricocirignaco/infrastructure
    type: git
    version: main
  - name: git+https://github.com/enricocirignaco/ansible.git#/ansible_collections/enricocirignaco/radxa
    type: git
    version: main
